export const TPM = {
  title: 'The Phantom Menace',
  episode_id: 1,
  characters: [
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 11, name: 'Anakin Skywalker'},
    { id: 16, name: 'Jabba Desilijic Tiure'},
    { id: 20, name: 'Yoda'},
    { id: 21, name: 'Palpatine'},
    { id: 32, name: 'Qui-Gon Jinn'},
    { id: 33, name: 'Nute Gunray'},
    { id: 34, name: 'Finis Valorum'},
    { id: 35, name: 'Padmé Amidala'},
    { id: 36, name: 'Jar Jar Binks'},
    { id: 37, name: 'Roos Tarpals'},
    { id: 38, name: 'Rugor Nass'},
    { id: 39, name: 'Ric Olié'},
    { id: 40, name: 'Watto'},
    { id: 41, name: 'Sebulba'},
    { id: 42, name: 'Quarsh Panaka'},
    { id: 43, name: 'Shmi Skywalker'},
    { id: 44, name: 'Darth Maul'},
    { id: 46, name: 'Ayla Secura'},
    { id: 47, name: 'Ratts Tyerell'},
    { id: 48, name: 'Dud Bolt'},
    { id: 49, name: 'Gasgano'},
    { id: 50, name: 'Ben Quadrinaros'},
    { id: 51, name: 'Mace Windu'},
    { id: 52, name: 'Ki-Adi-Mundi'},
    { id: 53, name: 'Kit Fisto'},
    { id: 54, name: 'Eeth Koth'},
    { id: 55, name: 'Adi Gallia'},
    { id: 56, name: 'Sasee Tiin'},
    { id: 57, name: 'Yarael Poof'},
    { id: 58, name: 'Plo Koon'},
    { id: 59, name: 'Mas Amedda'},

  ],
  planets: [
    { id: 1, name: 'Tatooine'},
    { id: 8, name: 'Naboo'},
    { id: 9, name: 'Coruscant'}
  ],
  starships: [
    { id: 31, name: 'Republic Cruiser'},
    { id: 32, name: 'Droid Control Ship'},
    { id: 39, name: 'Naboo Fighter'},
    { id: 40, name: 'Naboo Royal Starship'},
    { id: 41, name: 'Scimitar'}
  ],
  vehicles: [
    { id: 33, name: 'Vulture Droid'},
    { id: 34, name: 'Multi-Troop Transport'},
    { id: 35, name: 'Armored Assault Tank'},
    { id: 36, name: 'Single Trooper Aerial Platform'},
    { id: 37, name: 'C-9979 Landing Craft'},
    { id: 38, name: 'Tribubble Bongo'},
    { id: 42, name: 'Sith Speeder'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 6, name: 'Yoda\'s Species'},
    { id: 11, name: 'Neimodian'},
    { id: 12, name: 'Gungan'},
    { id: 13, name: 'Toydarian'},
    { id: 14, name: 'Dug'},
    { id: 15, name: 'Twi\'lek'},
    { id: 16, name: 'Aleena'},
    { id: 17, name: 'Vulptereen'},
    { id: 18, name: 'Xexto'},
    { id: 19, name: 'Toong'},
    { id: 20, name: 'Cerean'},
    { id: 21, name: 'Nautolan'},
    { id: 22, name: 'Zabrak'},
    { id: 23, name: 'Tholothian'},
    { id: 24, name: 'Iktotchi'},
    { id: 25, name: 'Quermian'},
    { id: 26, name: 'Kel Dor'},
    { id: 27, name: 'Chagrian'}
  ],
  url: 'https://swapi.co/api/films/4/'
};

export const AOTC = {
  title: 'Attack of the Clones',
  episode_id: 2,
  characters: [
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 6, name: 'Owen Lars'},
    { id: 7, name: 'Beru Whitesun Lars'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 11, name: 'Anakin Skywalker'},
    { id: 20, name: 'Yoda'},
    { id: 21, name: 'Palpatine'},
    { id: 22, name: 'Boba Fett'},
    { id: 33, name: 'Nute Gunray'},
    { id: 35, name: 'Padmé Amidala'},
    { id: 36, name: 'Jar Jar Binks'},
    { id: 40, name: 'Watto'},
    { id: 43, name: 'Shmi Skywalker'},
    { id: 46, name: 'Ayla Secura'},
    { id: 51, name: 'Mace Windu'},
    { id: 52, name: 'Ki-Adi-Mundi'},
    { id: 53, name: 'Kit Fisto'},
    { id: 58, name: 'Plo Koon'},
    { id: 59, name: 'Mas Amedda'},
    { id: 60, name: 'Gregar Typho'},
    { id: 61, name: 'Cordé'},
    { id: 62, name: 'Cliegg Lars'},
    { id: 63, name: 'Poggle the Lesser'},
    { id: 64, name: 'Luminara Unduli'},
    { id: 65, name: 'Barriss Offee'},
    { id: 66, name: 'Dormé'},
    { id: 67, name: 'Dooku'},
    { id: 68, name: 'Bail Prestor Organa'},
    { id: 69, name: 'Jango Fett'},
    { id: 70, name: 'Zam Wesell'},
    { id: 71, name: 'Dexter Jettster'},
    { id: 72, name: 'Lama Su'},
    { id: 73, name: 'Taun We'},
    { id: 74, name: 'Jocasta Nu'},
    { id: 75, name: 'R4-P17'},
    { id: 76, name: 'Wat Tambor'},
    { id: 77, name: 'San Hill'},
    { id: 78, name: 'Shaak Ti'},
    { id: 82, name: 'Sly Moore'}
  ],
  planets: [
    { id: 1, name: 'Tatooine'},
    { id: 8, name: 'Naboo'},
    { id: 9, name: 'Coruscant'},
    { id: 10, name: 'Kamino'},
    { id: 11, name: 'Geonosis'}
  ],
  starships: [
    { id: 21, name: 'Slave 1'},
    { id: 32, name: 'Droid Control Ship'},
    { id: 39, name: 'Naboo Fighter'},
    { id: 43, name: 'J-Type Diplomatic Barge'},
    { id: 47, name: 'AA-9 Coruscant Freighter'},
    { id: 48, name: 'Jedi Starfighter'},
    { id: 49, name: 'H-Type Nubian Yacht'},
    { id: 52, name: 'Republic Assault Ship'},
    { id: 58, name: 'Solar Sailer'}
  ],
  vehicles: [
    { id: 4, name: 'Sand Crawler'},
    { id: 44, name: 'Zephyr-G Swoop Bike'},
    { id: 45, name: 'Koro-2 Exodrive Airspeeder'},
    { id: 46, name: 'XJ-6 Airspeeder'},
    { id: 50, name: 'LAAT/I'},
    { id: 51, name: 'LAAT/C'},
    { id: 53, name: 'AT-TE'},
    { id: 54, name: 'SPHA'},
    { id: 55, name: 'Flitknot Speeder'},
    { id: 56, name: 'Neimoidian Shuttle'},
    { id: 57, name: 'Geonosian Starfighter'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 6, name: 'Yoda\'s Species'},
    { id: 12, name: 'Gungan'},
    { id: 13, name: 'Toydarian'},
    { id: 15, name: 'Twi\'lek'},
    { id: 28, name: 'Geonosian'},
    { id: 29, name: 'Mirialan'},
    { id: 30, name: 'Clawdite'},
    { id: 31, name: 'Besalisk'},
    { id: 32, name: 'Kaminoan'},
    { id: 33, name: 'Skakoan'},
    { id: 34, name: 'Muun'},
    { id: 35, name: 'Togruta'}
  ],
  url: 'https://swapi.co/api/films/5/'

};

export const ROTS = {
  title: 'Revenge of the Sith',
  episode_id: 3,
  characters: [
    { id: 1, name: 'Luke Skywalker'},
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 4, name: 'Darth Vader'},
    { id: 5, name: 'Leia Organa'},
    { id: 6, name: 'Owen Lars'},
    { id: 7, name: 'Beru Whitesun Lars'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 11, name: 'Anakin Skywalker'},
    { id: 12, name: 'Wilhuff Tarkin'},
    { id: 13, name: 'Chewbacca'},
    { id: 20, name: 'Yoda'},
    { id: 21, name: 'Palpatine'},
    { id: 33, name: 'Nute Gunray'},
    { id: 35, name: 'Padmé Amidala'},
    { id: 46, name: 'Ayla Secura'},
    { id: 51, name: 'Mace Windu'},
    { id: 52, name: 'Ki-Adi-Mundi'},
    { id: 53, name: 'Kit Fisto'},
    { id: 54, name: 'Eeth Koth'},
    { id: 55, name: 'Adi Gallia'},
    { id: 56, name: 'Sasee Tiin'},
    { id: 58, name: 'Plo Koon'},
    { id: 63, name: 'Poggle the Lesser'},
    { id: 64, name: 'Luminara Unduli'},
    { id: 67, name: 'Dooku'},
    { id: 68, name: 'Bail Prestor Organa'},
    { id: 75, name: 'R4-P17'},
    { id: 78, name: 'Shaak Ti'},
    { id: 79, name: 'Grievous'},
    { id: 80, name: 'Tarrful'},
    { id: 81, name: 'Raymus Antilles'},
    { id: 82, name: 'Sly Moore'},
    { id: 83, name: 'Tion Medon'}
  ],
  planets: [
    { id: 1, name: 'Tatooine'},
    { id: 2, name: 'Alderaan'},
    { id: 5, name: 'Dagobah'},
    { id: 8, name: 'Naboo'},
    { id: 9, name: 'Coruscant'},
    { id: 12, name: 'Utapau'},
    { id: 13, name: 'Mustafar'},
    { id: 14, name: 'Kashyyyk'},
    { id: 15, name: 'Polis Massa'},
    { id: 16, name: 'Mygeeto'},
    { id: 17, name: 'Felucia'},
    { id: 18, name: 'Cato Neimoidia'},
    { id: 19, name: 'Saleucami'}
  ],
  starships: [
    { id: 2, name: 'CR90 Corvette'},
    { id: 32, name: 'Droid Control Ship'},
    { id: 48, name: 'Jedi Starfighter'},
    { id: 59, name: 'Trade Federation Cruiser'},
    { id: 61, name: 'Theta-Class T-2C Shuttle'},
    { id: 63, name: 'Republic Attack Cruiser'},
    { id: 64, name: 'Naboo Star Skiff'},
    { id: 65, name: 'Jedi Interceptor'},
    { id: 66, name: 'ARC-170'},
    { id: 68, name: 'Banking Clan Frigate'},
    { id: 74, name: 'Belbullab-22 Starfighter'},
    { id: 75, name: 'V-Wing'}
  ],
  vehicles: [
    { id: 33, name: 'Vulture Droid'},
    { id: 50, name: 'LAAT/I'},
    { id: 53, name: 'AT-TE'},
    { id: 56, name: 'Neimoidian Shuttle'},
    { id: 60, name: 'Tsmeu-6 Personal Wheel Bike'},
    { id: 62, name: 'Emergency Firespeeder'},
    { id: 67, name: 'Droid Tri-Fighter'},
    { id: 69, name: 'Oevvaor Jet Catamaran'},
    { id: 70, name: 'Raddaugh Gnasp Fluttercraft'},
    { id: 71, name: 'Clone Turbo Tank'},
    { id: 72, name: 'Corporate Alliance Tank Droid'},
    { id: 73, name: 'Droid Gunship'},
    { id: 76, name: 'AT-RT'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 3, name: 'Wookiee'},
    { id: 6, name: 'Yoda\'s Species'},
    { id: 15, name: 'Twi\'lek'},
    { id: 19, name: 'Toong'},
    { id: 20, name: 'Cerean'},
    { id: 23, name: 'Tholothian'},
    { id: 24, name: 'Iktotchi'},
    { id: 25, name: 'Quermian'},
    { id: 26, name: 'Kel Dor'},
    { id: 27, name: 'Chagrian'},
    { id: 28, name: 'Geonosian'},
    { id: 29, name: 'Mirialan'},
    { id: 30, name: 'Clawdite'},
    { id: 33, name: 'Skakoan'},
    { id: 34, name: 'Muun'},
    { id: 35, name: 'Togruta'},
    { id: 36, name: 'Kaleesh'},
    { id: 37, name: 'Paun\'an'}
  ],
  url: 'https://swapi.co/api/films/6'
};

export const ANH = {
  title: 'A New Hope',
  episode_id: 4,
  characters: [
    { id: 1, name: 'Luke Skywalker'},
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 4, name: 'Darth Vader'},
    { id: 5, name: 'Leia Organa'},
    { id: 6, name: 'Owen Lars'},
    { id: 7, name: 'Beru Whitesun Lars'},
    { id: 8, name: 'R5-D4'},
    { id: 9, name: 'Biggs Darklighter'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 12, name: 'Wilhuff Tarkin'},
    { id: 13, name: 'Chewbacca'},
    { id: 14, name: 'Han Solo'},
    { id: 15, name: 'Greedo'},
    { id: 16, name: 'Jabba Desilijic Tiure'},
    { id: 18, name: 'Wedge Antilles'},
    { id: 19, name: 'Jek Tono Porkins'},
    { id: 81, name: 'Raymus Antilles'}
  ],
  planets: [
    { id: 1, name: 'Tatooine'},
    { id: 2, name: 'Alderaan'},
    { id: 3, name: 'Yavin IV'}

  ],
  starships: [
    { id: 2, name: 'CR90 Corvette'},
    { id: 3, name: 'Star Destroyer'},
    { id: 5, name: 'Sentinel-Class Landing Craft'},
    { id: 9, name: 'Death Star'},
    { id: 10, name: 'Millennium Falcon'},
    { id: 11, name: 'Y-Wing'},
    { id: 12, name: 'X-Wing'},
    { id: 13, name: 'TIE Advanced X1'}

  ],
  vehicles: [
    { id: 4, name: 'Sand Crawler'},
    { id: 6, name: 'T-16 Skyhopper'},
    { id: 7, name: 'X-34 Landspeeder'},
    { id: 8, name: 'TIE/LN Starfighter'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 3, name: 'Wookiee'},
    { id: 4, name: 'Rodian'},
    { id: 5, name: 'Hutt'}
  ],
  url: 'https://swapi.co/api/films/1'
};

export const TESB = {
  title: 'The Empire Strikes Back',
  episode_id: 5,
  characters: [
    { id: 1, name: 'Luke Skywalker'},
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 4, name: 'Darth Vader'},
    { id: 5, name: 'Leia Organa'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 13, name: 'Chewbacca'},
    { id: 14, name: 'Han Solo'},
    { id: 18, name: 'Wedge Antilles'},
    { id: 20, name: 'Yoda'},
    { id: 21, name: 'Palpatine'},
    { id: 22, name: 'Boba Fett'},
    { id: 23, name: 'IG-88'},
    { id: 24, name: 'Bossk'},
    { id: 25, name: 'Lando Calrissian'},
    { id: 26, name: 'Lobot'}
  ],
  planets: [
    { id: 4, name: 'Hoth'},
    { id: 5, name: 'Dagobah'},
    { id: 6, name: 'Bespin'},
    { id: 27, name: 'Ord Mantell'}
  ],
  starships: [
    { id: 3, name: 'Star Destroyer'},
    { id: 10, name: 'Millennium Falcon'},
    { id: 11, name: 'Y-Wing'},
    { id: 12, name: 'X-Wing'},
    { id: 15, name: 'Executor'},
    { id: 17, name: 'Rebel Transport'},
    { id: 21, name: 'Slave 1'},
    { id: 22, name: 'Imperial Shuttle'},
    { id: 23, name: 'EF76 Nebula-B Escort Frigate'}
  ],
  vehicles: [
    { id: 8, name: 'TIE/LN Starfighter'},
    { id: 14, name: 'Snowspeeder'},
    { id: 16, name: 'TIE Bomber'},
    { id: 18, name: 'AT-AT'},
    { id: 19, name: 'AT-ST'},
    { id: 20, name: 'Storm IV Twin-Pod Cloud Car'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 3, name: 'Wookiee'},
    { id: 6, name: 'Yoda\'s Species'},
    { id: 7, name: 'Trandoshan'}
  ],
  url: 'https://swapi.co/api/films/2'
};

export const ROTJ = {
  title: 'Return of the Jedi',
  episode_id: 6,
  characters: [
    { id: 1, name: 'Luke Skywalker'},
    { id: 2, name: 'C-3P0'},
    { id: 3, name: 'R2-D2'},
    { id: 4, name: 'Darth Vader'},
    { id: 5, name: 'Leia Organa'},
    { id: 10, name: 'Obi-Wan Kenobi'},
    { id: 13, name: 'Chewbacca'},
    { id: 14, name: 'Han Solo'},
    { id: 16, name: 'Jabba Desilijic Tiure'},
    { id: 18, name: 'Wedge Antilles'},
    { id: 20, name: 'Yoda'},
    { id: 21, name: 'Palpatine'},
    { id: 22, name: 'Boba Fett'},
    { id: 25, name: 'Lando Calrissian'},
    { id: 27, name: 'Ackbar'},
    { id: 28, name: 'Mon Mothma'},
    { id: 29, name: 'Arvel Crynyd'},
    { id: 30, name: 'Wicket Systri Warrick'},
    { id: 31, name: 'Nien Nunb'},
    { id: 45, name: 'Bib Fortuna'}
  ],
  planets: [
    { id: 1, name: 'Tatooine'},
    { id: 5, name: 'Dagobah'},
    { id: 7, name: 'Endor'},
    { id: 8, name: 'Naboo'},
    { id: 9, name: 'Coruscant'}
  ],
  starships: [
    { id: 2, name: 'CR90-Corvette'},
    { id: 3, name: 'Star Destroyer'},
    { id: 10, name: 'Millennium Falcon'},
    { id: 11, name: 'Y-Wing'},
    { id: 12, name: 'X-Wing'},
    { id: 15, name: 'Executor'},
    { id: 17, name: 'Rebel Transport'},
    { id: 22, name: 'Imperial Shuttle'},
    { id: 23, name: 'EF76 Nebula-B Escort Frigate'},
    { id: 27, name: 'Calamari Cruiser'},
    { id: 28, name: 'A-Wing'},
    { id: 29, name: 'B-Wing'}
  ],
  vehicles: [
    { id: 8, name: 'TIE/LN Starfighter'},
    { id: 16, name: 'TIE Bomber'},
    { id: 18, name: 'AT-AT'},
    { id: 19, name: 'AT-ST'},
    { id: 24, name: 'Sail Barge'},
    { id: 25, name: 'Bantha-II Cargo Skiff'},
    { id: 26, name: 'TIE/IN Interceptor'},
    { id: 30, name: 'Imperial Speeder Bike'}
  ],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 3, name: 'Wookiee'},
    { id: 5, name: 'Hutt'},
    { id: 6, name: 'Yoda\'s Species'},
    { id: 8, name: 'Mon Calamari'},
    { id: 9, name: 'Ewok'},
    { id: 10, name: 'Sullustan'},
    { id: 15, name: 'Twi\'lek'}
  ],
  url: 'https://swapi.co/api/films/3'
};

export const TFA = {
  title: 'The Force Awakens',
  episode_id: 7,
  characters: [
    { id: 1, name: 'Luke Skywalker'},
    { id: 3, name: 'R2-D2'},
    { id: 5, name: 'Leia Organa'},
    { id: 13, name: 'Chewbacca'},
    { id: 14, name: 'Han Solo'},
    { id: 27, name: 'Ackbar'},
    { id: 84, name: 'Finn'},
    { id: 85, name: 'Rey'},
    { id: 86, name: 'Poe Dameron'},
    { id: 87, name: 'BB8'},
    { id: 88, name: 'Captain Phasma'}
  ],
  planets: [
    { id: 61, name: 'Jakku'}
  ],
  starships: [
    { id: 10, name: 'Millenium Falcon'},
    { id: 77, name: 'T-70 X-Wing Fighter'}
  ],
  vehicles: [],
  species: [
    { id: 1, name: 'Human'},
    { id: 2, name: 'Droid'},
    { id: 3, name: 'Wookiee'}
  ],
  url: 'https://swapi.co/api/films/7'
};